// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/snapshots.proto

package src;

public final class SP {
  private SP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShapeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Shape)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required double pos_x = 2;</code>
     */
    boolean hasPosX();
    /**
     * <code>required double pos_x = 2;</code>
     */
    double getPosX();

    /**
     * <code>required double pos_y = 3;</code>
     */
    boolean hasPosY();
    /**
     * <code>required double pos_y = 3;</code>
     */
    double getPosY();

    /**
     * <code>required double size_x = 4;</code>
     */
    boolean hasSizeX();
    /**
     * <code>required double size_x = 4;</code>
     */
    double getSizeX();

    /**
     * <code>required double size_y = 5;</code>
     */
    boolean hasSizeY();
    /**
     * <code>required double size_y = 5;</code>
     */
    double getSizeY();

    /**
     * <code>optional double vel_x = 6;</code>
     */
    boolean hasVelX();
    /**
     * <code>optional double vel_x = 6;</code>
     */
    double getVelX();

    /**
     * <code>optional double vel_y = 7;</code>
     */
    boolean hasVelY();
    /**
     * <code>optional double vel_y = 7;</code>
     */
    double getVelY();

    /**
     * <code>optional double accel_x = 8;</code>
     */
    boolean hasAccelX();
    /**
     * <code>optional double accel_x = 8;</code>
     */
    double getAccelX();

    /**
     * <code>optional double accel_y = 9;</code>
     */
    boolean hasAccelY();
    /**
     * <code>optional double accel_y = 9;</code>
     */
    double getAccelY();
  }
  /**
   * Protobuf type {@code Shape}
   */
  public  static final class Shape extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Shape)
      ShapeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Shape.newBuilder() to construct.
    private Shape(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Shape() {
      type_ = "";
      posX_ = 0D;
      posY_ = 0D;
      sizeX_ = 0D;
      sizeY_ = 0D;
      velX_ = 0D;
      velY_ = 0D;
      accelX_ = 0D;
      accelY_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Shape(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              posX_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              posY_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              sizeX_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              sizeY_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              velX_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              velY_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              accelX_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              accelY_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.SP.internal_static_Shape_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.SP.internal_static_Shape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.SP.Shape.class, src.SP.Shape.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POS_X_FIELD_NUMBER = 2;
    private double posX_;
    /**
     * <code>required double pos_x = 2;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double pos_x = 2;</code>
     */
    public double getPosX() {
      return posX_;
    }

    public static final int POS_Y_FIELD_NUMBER = 3;
    private double posY_;
    /**
     * <code>required double pos_y = 3;</code>
     */
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double pos_y = 3;</code>
     */
    public double getPosY() {
      return posY_;
    }

    public static final int SIZE_X_FIELD_NUMBER = 4;
    private double sizeX_;
    /**
     * <code>required double size_x = 4;</code>
     */
    public boolean hasSizeX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double size_x = 4;</code>
     */
    public double getSizeX() {
      return sizeX_;
    }

    public static final int SIZE_Y_FIELD_NUMBER = 5;
    private double sizeY_;
    /**
     * <code>required double size_y = 5;</code>
     */
    public boolean hasSizeY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double size_y = 5;</code>
     */
    public double getSizeY() {
      return sizeY_;
    }

    public static final int VEL_X_FIELD_NUMBER = 6;
    private double velX_;
    /**
     * <code>optional double vel_x = 6;</code>
     */
    public boolean hasVelX() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double vel_x = 6;</code>
     */
    public double getVelX() {
      return velX_;
    }

    public static final int VEL_Y_FIELD_NUMBER = 7;
    private double velY_;
    /**
     * <code>optional double vel_y = 7;</code>
     */
    public boolean hasVelY() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double vel_y = 7;</code>
     */
    public double getVelY() {
      return velY_;
    }

    public static final int ACCEL_X_FIELD_NUMBER = 8;
    private double accelX_;
    /**
     * <code>optional double accel_x = 8;</code>
     */
    public boolean hasAccelX() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double accel_x = 8;</code>
     */
    public double getAccelX() {
      return accelX_;
    }

    public static final int ACCEL_Y_FIELD_NUMBER = 9;
    private double accelY_;
    /**
     * <code>optional double accel_y = 9;</code>
     */
    public boolean hasAccelY() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double accel_y = 9;</code>
     */
    public double getAccelY() {
      return accelY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSizeX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSizeY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, sizeX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, sizeY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, velX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, velY_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, accelX_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, accelY_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, sizeX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, sizeY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, velX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, velY_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, accelX_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, accelY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.SP.Shape)) {
        return super.equals(obj);
      }
      src.SP.Shape other = (src.SP.Shape) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasPosX() == other.hasPosX());
      if (hasPosX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getPosX())
            == java.lang.Double.doubleToLongBits(
                other.getPosX()));
      }
      result = result && (hasPosY() == other.hasPosY());
      if (hasPosY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getPosY())
            == java.lang.Double.doubleToLongBits(
                other.getPosY()));
      }
      result = result && (hasSizeX() == other.hasSizeX());
      if (hasSizeX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSizeX())
            == java.lang.Double.doubleToLongBits(
                other.getSizeX()));
      }
      result = result && (hasSizeY() == other.hasSizeY());
      if (hasSizeY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSizeY())
            == java.lang.Double.doubleToLongBits(
                other.getSizeY()));
      }
      result = result && (hasVelX() == other.hasVelX());
      if (hasVelX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getVelX())
            == java.lang.Double.doubleToLongBits(
                other.getVelX()));
      }
      result = result && (hasVelY() == other.hasVelY());
      if (hasVelY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getVelY())
            == java.lang.Double.doubleToLongBits(
                other.getVelY()));
      }
      result = result && (hasAccelX() == other.hasAccelX());
      if (hasAccelX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getAccelX())
            == java.lang.Double.doubleToLongBits(
                other.getAccelX()));
      }
      result = result && (hasAccelY() == other.hasAccelY());
      if (hasAccelY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getAccelY())
            == java.lang.Double.doubleToLongBits(
                other.getAccelY()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasPosX()) {
        hash = (37 * hash) + POS_X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPosX()));
      }
      if (hasPosY()) {
        hash = (37 * hash) + POS_Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPosY()));
      }
      if (hasSizeX()) {
        hash = (37 * hash) + SIZE_X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSizeX()));
      }
      if (hasSizeY()) {
        hash = (37 * hash) + SIZE_Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSizeY()));
      }
      if (hasVelX()) {
        hash = (37 * hash) + VEL_X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVelX()));
      }
      if (hasVelY()) {
        hash = (37 * hash) + VEL_Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVelY()));
      }
      if (hasAccelX()) {
        hash = (37 * hash) + ACCEL_X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAccelX()));
      }
      if (hasAccelY()) {
        hash = (37 * hash) + ACCEL_Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAccelY()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.SP.Shape parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Shape parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Shape parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Shape parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Shape parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Shape parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Shape parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Shape parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Shape parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.SP.Shape parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Shape parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Shape parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.SP.Shape prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Shape}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Shape)
        src.SP.ShapeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.SP.internal_static_Shape_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.SP.internal_static_Shape_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.SP.Shape.class, src.SP.Shape.Builder.class);
      }

      // Construct using src.SP.Shape.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        posX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        posY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        sizeX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        sizeY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        velX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        velY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        accelX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        accelY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.SP.internal_static_Shape_descriptor;
      }

      public src.SP.Shape getDefaultInstanceForType() {
        return src.SP.Shape.getDefaultInstance();
      }

      public src.SP.Shape build() {
        src.SP.Shape result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.SP.Shape buildPartial() {
        src.SP.Shape result = new src.SP.Shape(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posY_ = posY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sizeX_ = sizeX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sizeY_ = sizeY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.velX_ = velX_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.velY_ = velY_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.accelX_ = accelX_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.accelY_ = accelY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.SP.Shape) {
          return mergeFrom((src.SP.Shape)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.SP.Shape other) {
        if (other == src.SP.Shape.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        if (other.hasSizeX()) {
          setSizeX(other.getSizeX());
        }
        if (other.hasSizeY()) {
          setSizeY(other.getSizeY());
        }
        if (other.hasVelX()) {
          setVelX(other.getVelX());
        }
        if (other.hasVelY()) {
          setVelY(other.getVelY());
        }
        if (other.hasAccelX()) {
          setAccelX(other.getAccelX());
        }
        if (other.hasAccelY()) {
          setAccelY(other.getAccelY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasPosX()) {
          return false;
        }
        if (!hasPosY()) {
          return false;
        }
        if (!hasSizeX()) {
          return false;
        }
        if (!hasSizeY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.SP.Shape parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.SP.Shape) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private double posX_ ;
      /**
       * <code>required double pos_x = 2;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double pos_x = 2;</code>
       */
      public double getPosX() {
        return posX_;
      }
      /**
       * <code>required double pos_x = 2;</code>
       */
      public Builder setPosX(double value) {
        bitField0_ |= 0x00000002;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double pos_x = 2;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        posX_ = 0D;
        onChanged();
        return this;
      }

      private double posY_ ;
      /**
       * <code>required double pos_y = 3;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double pos_y = 3;</code>
       */
      public double getPosY() {
        return posY_;
      }
      /**
       * <code>required double pos_y = 3;</code>
       */
      public Builder setPosY(double value) {
        bitField0_ |= 0x00000004;
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double pos_y = 3;</code>
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posY_ = 0D;
        onChanged();
        return this;
      }

      private double sizeX_ ;
      /**
       * <code>required double size_x = 4;</code>
       */
      public boolean hasSizeX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double size_x = 4;</code>
       */
      public double getSizeX() {
        return sizeX_;
      }
      /**
       * <code>required double size_x = 4;</code>
       */
      public Builder setSizeX(double value) {
        bitField0_ |= 0x00000008;
        sizeX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double size_x = 4;</code>
       */
      public Builder clearSizeX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sizeX_ = 0D;
        onChanged();
        return this;
      }

      private double sizeY_ ;
      /**
       * <code>required double size_y = 5;</code>
       */
      public boolean hasSizeY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double size_y = 5;</code>
       */
      public double getSizeY() {
        return sizeY_;
      }
      /**
       * <code>required double size_y = 5;</code>
       */
      public Builder setSizeY(double value) {
        bitField0_ |= 0x00000010;
        sizeY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double size_y = 5;</code>
       */
      public Builder clearSizeY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sizeY_ = 0D;
        onChanged();
        return this;
      }

      private double velX_ ;
      /**
       * <code>optional double vel_x = 6;</code>
       */
      public boolean hasVelX() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double vel_x = 6;</code>
       */
      public double getVelX() {
        return velX_;
      }
      /**
       * <code>optional double vel_x = 6;</code>
       */
      public Builder setVelX(double value) {
        bitField0_ |= 0x00000020;
        velX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vel_x = 6;</code>
       */
      public Builder clearVelX() {
        bitField0_ = (bitField0_ & ~0x00000020);
        velX_ = 0D;
        onChanged();
        return this;
      }

      private double velY_ ;
      /**
       * <code>optional double vel_y = 7;</code>
       */
      public boolean hasVelY() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double vel_y = 7;</code>
       */
      public double getVelY() {
        return velY_;
      }
      /**
       * <code>optional double vel_y = 7;</code>
       */
      public Builder setVelY(double value) {
        bitField0_ |= 0x00000040;
        velY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vel_y = 7;</code>
       */
      public Builder clearVelY() {
        bitField0_ = (bitField0_ & ~0x00000040);
        velY_ = 0D;
        onChanged();
        return this;
      }

      private double accelX_ ;
      /**
       * <code>optional double accel_x = 8;</code>
       */
      public boolean hasAccelX() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double accel_x = 8;</code>
       */
      public double getAccelX() {
        return accelX_;
      }
      /**
       * <code>optional double accel_x = 8;</code>
       */
      public Builder setAccelX(double value) {
        bitField0_ |= 0x00000080;
        accelX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double accel_x = 8;</code>
       */
      public Builder clearAccelX() {
        bitField0_ = (bitField0_ & ~0x00000080);
        accelX_ = 0D;
        onChanged();
        return this;
      }

      private double accelY_ ;
      /**
       * <code>optional double accel_y = 9;</code>
       */
      public boolean hasAccelY() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double accel_y = 9;</code>
       */
      public double getAccelY() {
        return accelY_;
      }
      /**
       * <code>optional double accel_y = 9;</code>
       */
      public Builder setAccelY(double value) {
        bitField0_ |= 0x00000100;
        accelY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double accel_y = 9;</code>
       */
      public Builder clearAccelY() {
        bitField0_ = (bitField0_ & ~0x00000100);
        accelY_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Shape)
    }

    // @@protoc_insertion_point(class_scope:Shape)
    private static final src.SP.Shape DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.SP.Shape();
    }

    public static src.SP.Shape getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Shape>
        PARSER = new com.google.protobuf.AbstractParser<Shape>() {
      public Shape parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Shape(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Shape> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Shape> getParserForType() {
      return PARSER;
    }

    public src.SP.Shape getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SnapshotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Snapshot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 1;</code>
     */
    double getTime();

    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    java.util.List<src.SP.Shape> 
        getShapesList();
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    src.SP.Shape getShapes(int index);
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    int getShapesCount();
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    java.util.List<? extends src.SP.ShapeOrBuilder> 
        getShapesOrBuilderList();
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    src.SP.ShapeOrBuilder getShapesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Snapshot}
   */
  public  static final class Snapshot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Snapshot)
      SnapshotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Snapshot() {
      time_ = 0D;
      shapes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              time_ = input.readDouble();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                shapes_ = new java.util.ArrayList<src.SP.Shape>();
                mutable_bitField0_ |= 0x00000002;
              }
              shapes_.add(
                  input.readMessage(src.SP.Shape.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          shapes_ = java.util.Collections.unmodifiableList(shapes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.SP.internal_static_Snapshot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.SP.internal_static_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.SP.Snapshot.class, src.SP.Snapshot.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private double time_;
    /**
     * <code>required double time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double time = 1;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int SHAPES_FIELD_NUMBER = 2;
    private java.util.List<src.SP.Shape> shapes_;
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    public java.util.List<src.SP.Shape> getShapesList() {
      return shapes_;
    }
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    public java.util.List<? extends src.SP.ShapeOrBuilder> 
        getShapesOrBuilderList() {
      return shapes_;
    }
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    public int getShapesCount() {
      return shapes_.size();
    }
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    public src.SP.Shape getShapes(int index) {
      return shapes_.get(index);
    }
    /**
     * <code>repeated .Shape shapes = 2;</code>
     */
    public src.SP.ShapeOrBuilder getShapesOrBuilder(
        int index) {
      return shapes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getShapesCount(); i++) {
        if (!getShapes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, time_);
      }
      for (int i = 0; i < shapes_.size(); i++) {
        output.writeMessage(2, shapes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, time_);
      }
      for (int i = 0; i < shapes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, shapes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.SP.Snapshot)) {
        return super.equals(obj);
      }
      src.SP.Snapshot other = (src.SP.Snapshot) obj;

      boolean result = true;
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getTime())
            == java.lang.Double.doubleToLongBits(
                other.getTime()));
      }
      result = result && getShapesList()
          .equals(other.getShapesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getTime()));
      }
      if (getShapesCount() > 0) {
        hash = (37 * hash) + SHAPES_FIELD_NUMBER;
        hash = (53 * hash) + getShapesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.SP.Snapshot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.SP.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.SP.Snapshot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Snapshot)
        src.SP.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.SP.internal_static_Snapshot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.SP.internal_static_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.SP.Snapshot.class, src.SP.Snapshot.Builder.class);
      }

      // Construct using src.SP.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getShapesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (shapesBuilder_ == null) {
          shapes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          shapesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.SP.internal_static_Snapshot_descriptor;
      }

      public src.SP.Snapshot getDefaultInstanceForType() {
        return src.SP.Snapshot.getDefaultInstance();
      }

      public src.SP.Snapshot build() {
        src.SP.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.SP.Snapshot buildPartial() {
        src.SP.Snapshot result = new src.SP.Snapshot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (shapesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            shapes_ = java.util.Collections.unmodifiableList(shapes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.shapes_ = shapes_;
        } else {
          result.shapes_ = shapesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.SP.Snapshot) {
          return mergeFrom((src.SP.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.SP.Snapshot other) {
        if (other == src.SP.Snapshot.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (shapesBuilder_ == null) {
          if (!other.shapes_.isEmpty()) {
            if (shapes_.isEmpty()) {
              shapes_ = other.shapes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureShapesIsMutable();
              shapes_.addAll(other.shapes_);
            }
            onChanged();
          }
        } else {
          if (!other.shapes_.isEmpty()) {
            if (shapesBuilder_.isEmpty()) {
              shapesBuilder_.dispose();
              shapesBuilder_ = null;
              shapes_ = other.shapes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              shapesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getShapesFieldBuilder() : null;
            } else {
              shapesBuilder_.addAllMessages(other.shapes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          return false;
        }
        for (int i = 0; i < getShapesCount(); i++) {
          if (!getShapes(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.SP.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.SP.Snapshot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double time_ ;
      /**
       * <code>required double time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double time = 1;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<src.SP.Shape> shapes_ =
        java.util.Collections.emptyList();
      private void ensureShapesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          shapes_ = new java.util.ArrayList<src.SP.Shape>(shapes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          src.SP.Shape, src.SP.Shape.Builder, src.SP.ShapeOrBuilder> shapesBuilder_;

      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public java.util.List<src.SP.Shape> getShapesList() {
        if (shapesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shapes_);
        } else {
          return shapesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public int getShapesCount() {
        if (shapesBuilder_ == null) {
          return shapes_.size();
        } else {
          return shapesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public src.SP.Shape getShapes(int index) {
        if (shapesBuilder_ == null) {
          return shapes_.get(index);
        } else {
          return shapesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder setShapes(
          int index, src.SP.Shape value) {
        if (shapesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShapesIsMutable();
          shapes_.set(index, value);
          onChanged();
        } else {
          shapesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder setShapes(
          int index, src.SP.Shape.Builder builderForValue) {
        if (shapesBuilder_ == null) {
          ensureShapesIsMutable();
          shapes_.set(index, builderForValue.build());
          onChanged();
        } else {
          shapesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder addShapes(src.SP.Shape value) {
        if (shapesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShapesIsMutable();
          shapes_.add(value);
          onChanged();
        } else {
          shapesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder addShapes(
          int index, src.SP.Shape value) {
        if (shapesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShapesIsMutable();
          shapes_.add(index, value);
          onChanged();
        } else {
          shapesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder addShapes(
          src.SP.Shape.Builder builderForValue) {
        if (shapesBuilder_ == null) {
          ensureShapesIsMutable();
          shapes_.add(builderForValue.build());
          onChanged();
        } else {
          shapesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder addShapes(
          int index, src.SP.Shape.Builder builderForValue) {
        if (shapesBuilder_ == null) {
          ensureShapesIsMutable();
          shapes_.add(index, builderForValue.build());
          onChanged();
        } else {
          shapesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder addAllShapes(
          java.lang.Iterable<? extends src.SP.Shape> values) {
        if (shapesBuilder_ == null) {
          ensureShapesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, shapes_);
          onChanged();
        } else {
          shapesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder clearShapes() {
        if (shapesBuilder_ == null) {
          shapes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          shapesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public Builder removeShapes(int index) {
        if (shapesBuilder_ == null) {
          ensureShapesIsMutable();
          shapes_.remove(index);
          onChanged();
        } else {
          shapesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public src.SP.Shape.Builder getShapesBuilder(
          int index) {
        return getShapesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public src.SP.ShapeOrBuilder getShapesOrBuilder(
          int index) {
        if (shapesBuilder_ == null) {
          return shapes_.get(index);  } else {
          return shapesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public java.util.List<? extends src.SP.ShapeOrBuilder> 
           getShapesOrBuilderList() {
        if (shapesBuilder_ != null) {
          return shapesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shapes_);
        }
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public src.SP.Shape.Builder addShapesBuilder() {
        return getShapesFieldBuilder().addBuilder(
            src.SP.Shape.getDefaultInstance());
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public src.SP.Shape.Builder addShapesBuilder(
          int index) {
        return getShapesFieldBuilder().addBuilder(
            index, src.SP.Shape.getDefaultInstance());
      }
      /**
       * <code>repeated .Shape shapes = 2;</code>
       */
      public java.util.List<src.SP.Shape.Builder> 
           getShapesBuilderList() {
        return getShapesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          src.SP.Shape, src.SP.Shape.Builder, src.SP.ShapeOrBuilder> 
          getShapesFieldBuilder() {
        if (shapesBuilder_ == null) {
          shapesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              src.SP.Shape, src.SP.Shape.Builder, src.SP.ShapeOrBuilder>(
                  shapes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          shapes_ = null;
        }
        return shapesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Snapshot)
    }

    // @@protoc_insertion_point(class_scope:Snapshot)
    private static final src.SP.Snapshot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.SP.Snapshot();
    }

    public static src.SP.Snapshot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Snapshot>
        PARSER = new com.google.protobuf.AbstractParser<Snapshot>() {
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Snapshot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    public src.SP.Snapshot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SnapshotsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Snapshots)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    java.util.List<src.SP.Snapshot> 
        getSnapshotsList();
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    src.SP.Snapshot getSnapshots(int index);
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    int getSnapshotsCount();
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    java.util.List<? extends src.SP.SnapshotOrBuilder> 
        getSnapshotsOrBuilderList();
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    src.SP.SnapshotOrBuilder getSnapshotsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Snapshots}
   */
  public  static final class Snapshots extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Snapshots)
      SnapshotsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Snapshots.newBuilder() to construct.
    private Snapshots(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Snapshots() {
      snapshots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshots(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                snapshots_ = new java.util.ArrayList<src.SP.Snapshot>();
                mutable_bitField0_ |= 0x00000001;
              }
              snapshots_.add(
                  input.readMessage(src.SP.Snapshot.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.SP.internal_static_Snapshots_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.SP.internal_static_Snapshots_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.SP.Snapshots.class, src.SP.Snapshots.Builder.class);
    }

    public static final int SNAPSHOTS_FIELD_NUMBER = 1;
    private java.util.List<src.SP.Snapshot> snapshots_;
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    public java.util.List<src.SP.Snapshot> getSnapshotsList() {
      return snapshots_;
    }
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    public java.util.List<? extends src.SP.SnapshotOrBuilder> 
        getSnapshotsOrBuilderList() {
      return snapshots_;
    }
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    public int getSnapshotsCount() {
      return snapshots_.size();
    }
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    public src.SP.Snapshot getSnapshots(int index) {
      return snapshots_.get(index);
    }
    /**
     * <code>repeated .Snapshot snapshots = 1;</code>
     */
    public src.SP.SnapshotOrBuilder getSnapshotsOrBuilder(
        int index) {
      return snapshots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSnapshotsCount(); i++) {
        if (!getSnapshots(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < snapshots_.size(); i++) {
        output.writeMessage(1, snapshots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < snapshots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, snapshots_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.SP.Snapshots)) {
        return super.equals(obj);
      }
      src.SP.Snapshots other = (src.SP.Snapshots) obj;

      boolean result = true;
      result = result && getSnapshotsList()
          .equals(other.getSnapshotsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSnapshotsCount() > 0) {
        hash = (37 * hash) + SNAPSHOTS_FIELD_NUMBER;
        hash = (53 * hash) + getSnapshotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.SP.Snapshots parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshots parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshots parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshots parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshots parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.SP.Snapshots parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.SP.Snapshots parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Snapshots parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Snapshots parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.SP.Snapshots parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.SP.Snapshots parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.SP.Snapshots parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.SP.Snapshots prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Snapshots}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Snapshots)
        src.SP.SnapshotsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.SP.internal_static_Snapshots_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.SP.internal_static_Snapshots_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.SP.Snapshots.class, src.SP.Snapshots.Builder.class);
      }

      // Construct using src.SP.Snapshots.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSnapshotsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          snapshotsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.SP.internal_static_Snapshots_descriptor;
      }

      public src.SP.Snapshots getDefaultInstanceForType() {
        return src.SP.Snapshots.getDefaultInstance();
      }

      public src.SP.Snapshots build() {
        src.SP.Snapshots result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.SP.Snapshots buildPartial() {
        src.SP.Snapshots result = new src.SP.Snapshots(this);
        int from_bitField0_ = bitField0_;
        if (snapshotsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.snapshots_ = snapshots_;
        } else {
          result.snapshots_ = snapshotsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.SP.Snapshots) {
          return mergeFrom((src.SP.Snapshots)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.SP.Snapshots other) {
        if (other == src.SP.Snapshots.getDefaultInstance()) return this;
        if (snapshotsBuilder_ == null) {
          if (!other.snapshots_.isEmpty()) {
            if (snapshots_.isEmpty()) {
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSnapshotsIsMutable();
              snapshots_.addAll(other.snapshots_);
            }
            onChanged();
          }
        } else {
          if (!other.snapshots_.isEmpty()) {
            if (snapshotsBuilder_.isEmpty()) {
              snapshotsBuilder_.dispose();
              snapshotsBuilder_ = null;
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
              snapshotsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSnapshotsFieldBuilder() : null;
            } else {
              snapshotsBuilder_.addAllMessages(other.snapshots_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSnapshotsCount(); i++) {
          if (!getSnapshots(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.SP.Snapshots parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.SP.Snapshots) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<src.SP.Snapshot> snapshots_ =
        java.util.Collections.emptyList();
      private void ensureSnapshotsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          snapshots_ = new java.util.ArrayList<src.SP.Snapshot>(snapshots_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          src.SP.Snapshot, src.SP.Snapshot.Builder, src.SP.SnapshotOrBuilder> snapshotsBuilder_;

      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public java.util.List<src.SP.Snapshot> getSnapshotsList() {
        if (snapshotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snapshots_);
        } else {
          return snapshotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public int getSnapshotsCount() {
        if (snapshotsBuilder_ == null) {
          return snapshots_.size();
        } else {
          return snapshotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public src.SP.Snapshot getSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);
        } else {
          return snapshotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, src.SP.Snapshot value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.set(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, src.SP.Snapshot.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.set(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder addSnapshots(src.SP.Snapshot value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, src.SP.Snapshot value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder addSnapshots(
          src.SP.Snapshot.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, src.SP.Snapshot.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder addAllSnapshots(
          java.lang.Iterable<? extends src.SP.Snapshot> values) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snapshots_);
          onChanged();
        } else {
          snapshotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder clearSnapshots() {
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          snapshotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public Builder removeSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.remove(index);
          onChanged();
        } else {
          snapshotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public src.SP.Snapshot.Builder getSnapshotsBuilder(
          int index) {
        return getSnapshotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public src.SP.SnapshotOrBuilder getSnapshotsOrBuilder(
          int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);  } else {
          return snapshotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public java.util.List<? extends src.SP.SnapshotOrBuilder> 
           getSnapshotsOrBuilderList() {
        if (snapshotsBuilder_ != null) {
          return snapshotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snapshots_);
        }
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public src.SP.Snapshot.Builder addSnapshotsBuilder() {
        return getSnapshotsFieldBuilder().addBuilder(
            src.SP.Snapshot.getDefaultInstance());
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public src.SP.Snapshot.Builder addSnapshotsBuilder(
          int index) {
        return getSnapshotsFieldBuilder().addBuilder(
            index, src.SP.Snapshot.getDefaultInstance());
      }
      /**
       * <code>repeated .Snapshot snapshots = 1;</code>
       */
      public java.util.List<src.SP.Snapshot.Builder> 
           getSnapshotsBuilderList() {
        return getSnapshotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          src.SP.Snapshot, src.SP.Snapshot.Builder, src.SP.SnapshotOrBuilder> 
          getSnapshotsFieldBuilder() {
        if (snapshotsBuilder_ == null) {
          snapshotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              src.SP.Snapshot, src.SP.Snapshot.Builder, src.SP.SnapshotOrBuilder>(
                  snapshots_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          snapshots_ = null;
        }
        return snapshotsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Snapshots)
    }

    // @@protoc_insertion_point(class_scope:Snapshots)
    private static final src.SP.Snapshots DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.SP.Snapshots();
    }

    public static src.SP.Snapshots getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Snapshots>
        PARSER = new com.google.protobuf.AbstractParser<Snapshots>() {
      public Snapshots parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshots(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Snapshots> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshots> getParserForType() {
      return PARSER;
    }

    public src.SP.Snapshots getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Shape_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Shape_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Snapshot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Snapshot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Snapshots_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Snapshots_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023src/snapshots.proto\"\223\001\n\005Shape\022\014\n\004type\030" +
      "\001 \002(\t\022\r\n\005pos_x\030\002 \002(\001\022\r\n\005pos_y\030\003 \002(\001\022\016\n\006s" +
      "ize_x\030\004 \002(\001\022\016\n\006size_y\030\005 \002(\001\022\r\n\005vel_x\030\006 \001" +
      "(\001\022\r\n\005vel_y\030\007 \001(\001\022\017\n\007accel_x\030\010 \001(\001\022\017\n\007ac" +
      "cel_y\030\t \001(\001\"0\n\010Snapshot\022\014\n\004time\030\001 \002(\001\022\026\n" +
      "\006shapes\030\002 \003(\0132\006.Shape\")\n\tSnapshots\022\034\n\tsn" +
      "apshots\030\001 \003(\0132\t.SnapshotB\t\n\003srcB\002SP"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Shape_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Shape_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Shape_descriptor,
        new java.lang.String[] { "Type", "PosX", "PosY", "SizeX", "SizeY", "VelX", "VelY", "AccelX", "AccelY", });
    internal_static_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Snapshot_descriptor,
        new java.lang.String[] { "Time", "Shapes", });
    internal_static_Snapshots_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Snapshots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Snapshots_descriptor,
        new java.lang.String[] { "Snapshots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
